name: flutter_cache_manager
description: Generic cache manager for flutter
version: 0.2.0
author: Rene Floor <pub@renefloor.nl>
homepage: https://github.com/renefloor/flutter_cache_manager

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: "^0.4.0"
  path_provider: "^0.4.0"
  synchronized: "^1.5.1"
  uuid:  "^1.0.3"
  http: "^0.12.0"
  path: ^1.6.2
  sqflite: ^0.12.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
