name: flutter_cache_manager
description: Generic cache manager for flutter. Saves web files on the storages of the device and saves the cache info using sqflite.
version: 1.1.3
author: Rene Floor <pub@renefloor.nl>
homepage: https://github.com/renefloor/flutter_cache_manager

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ">=1.4.0"
  uuid:  "^2.0.2"
  http: ">=0.12.0+2"
  path: "^1.6.4"
  sqflite: "^1.1.7+2"
  pedantic: "^1.8.0+1"

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  file: ^5.1.0