name: flutter_cache_manager
description: Generic cache manager for flutter. Saves web files on the storages of the device and saves the cache info using sqflite.
version: 2.2.0-nullsafety.0
homepage: https://github.com/Baseflow/flutter_cache_manager

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.0-nullsafety
  uuid: ^3.0.0-nullsafety.0
  http: ^0.13.0-nullsafety.0
  path: ^1.8.0-nullsafety.3
  sqflite: ^2.0.0-nullsafety.3
  pedantic: ^1.10.0
  clock: ^1.1.0-nullsafety.3
  file: ^6.0.0-nullsafety.4
  rxdart: ^0.26.0-nullsafety.1
  image: ^3.0.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0-nullsafety.7
